version: '3'
name: solana

services:
  solana:
    image: solana_image
    container_name: solana
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - env/.env
